pipeline {
    agent any
    environment{
        INSTAGRAM_TAVO="@TAVO_GAMERO"
    }
    stages{
        stage("Saludo 1"){
            steps{
                echo "Hola desde saludo 1"
            }
        }
    }
}